# Generated by Django 2.0.4 on 2018-04-11 14:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_allotted', models.CharField(choices=[('None', 'None')], default='1', max_length=10)),
                ('room_no', models.CharField(default='0000', max_length=10)),
                ('room_type', models.CharField(choices=[('TYPE1', 'TYPE1'), ('TYPE2', 'TYPE2'), ('TYPE3', 'TYPE3')], default='TYPE1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_rooms_required', models.IntegerField(default=1)),
                ('from_date', models.DateField(default=datetime.date(2018, 4, 11))),
                ('to_date', models.DateField(default=datetime.date(2018, 4, 11))),
                ('date_of_booking', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Confirm Booking')),
                ('is_departed', models.BooleanField(default=False, verbose_name='Departed')),
                ('room_preference', models.CharField(choices=[('TYPE1', 'TYPE1'), ('TYPE2', 'TYPE2'), ('TYPE3', 'TYPE3')], default='TYPE1', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.Visitor'),
        ),
    ]
