# Generated by Django 2.0.3 on 2018-04-02 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_rooms_required', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('date_of_booking', models.DateTimeField(auto_now=True)),
                ('hostel_allotted', models.CharField(choices=[(1, 'VH1'), (2, 'VH2'), (3, 'VH3')], default=1, max_length=10)),
                ('rooms_allotted', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
