# Generated by Django 2.0.3 on 2018-04-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0007_auto_20180403_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='request_id',
            field=models.IntegerField(default=0),
        ),
    ]
