# Generated by Django 2.0.3 on 2018-04-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0009_auto_20180403_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='request_id',
        ),
    ]
