# Generated by Django 2.0.3 on 2018-04-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0010_remove_visitor_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_of_booking',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
